[package]
name = "mpm"
version = "0.1.0"
authors = ["alberto"]

[dependencies]
toml = "0.1"
rustc-serialize = "0.3"
rpf = "0.1"
pgetopts = "0.1"
tar = "0.3"
time = "0.1"
walkdir = "0.1"

[lib]
name = "util"
path = "lib/lib.rs"

[[bin]]
name = "mpm"
path = "src/main.rs"
test = false
