[package]
name = "mpm"
version = "0.1.0"
authors = ["alberto"]

[dependencies]
toml = "0.1.23"
rustc-serialize = "0.3"
rpf = "0.1.5"
pgetopts = "0.1.2"
tar = "0.3.1"
time = "0.1.32"
walkdir = "0.1.3"

[lib]
name = "util"
path = "lib/lib.rs"

[[bin]]
name = "mpm"
path = "src/main.rs"
test = false
