[package]
name = "mpm"
version = "0.1.0"
authors = ["alberto"]

[dependencies]
toml = "*"
rustc-serialize = "0.3"
rpf = "*"
pgetopts = "*"
tar = "*"
time = "*"

[lib]
name = "util"
path = "lib/lib.rs"

[[bin]]
name = "mpm"
path = "src/main.rs"
test = false
