[package]
name = "mpm"
version = "0.1.0"
authors = ["Alberto Corona <ac@albertocorona.com>"]

[dependencies]
rpf = "0.1"
pgetopts = "0.1"

[dependencies.libpm]
git = "https://gitlab.com/0X1A/libpm.git"

[[bin]]
name = "mpm"
path = "src/mpm.rs"
test = false
