name= "test"
vers = "0.0.1"
rel = "1"
arch = "any"
url = "https://github.com"
license = "BSD"
deps = ["make", "git", "rust"]
dest = "/usr"
conflicts = ["test-pkg-git"]

build = [
	"make"
]

install = [
	"make install"
]
