[package]
maintainers = [ "Alberto Corona<ac@albertocorona.com>" ]
desc = "Package file for testing mpm"
name = "hello-mpm"
vers = "0.0.1"
rel = "1"
arch = [""]
url = "https://github.com"
license = "BSD"
makedeps = ["make", "git"]
deps = [ ]
provides = "test"
prefix = "/usr"
conflicts = ["test-git"]
source = ["git+http://github.com/0X1A/hello-mpm"]
build = [
	'make',
	'make DEST=build install'
]

[clean]
script = [
	'rm hello-mpm-x86_64.pkg.tar',
	'rm -r build',
]
